version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_create_environment:
      - python -m pip install --no-cache-dir .[all]

conda:
  environment: .rtd-environment.yml
