name: regressproxy

channels:
    - conda-forge

dependencies:
    - python=3
    - numpy
    - pybind11
    - celerite
    - pymc3
    - pymc>=4
    - nbsphinx
    - numpydoc
    - ipython
    - pip
    - pip:
        - sphinx-markdown-tables
